---
name: PsyLib compilation and test
run-name: ${{ github.actor }} is compiling and testing PsyLib
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  Compile-psy-lib-Linux:
    strategy:
      matrix:
        compiler: [gcc, clang]
        buildtype: [debug, release]
    runs-on: ubuntu-22.04
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglib2.0-dev libgtk-4-dev libcunit1-dev
          version: 1.0
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install meson ninja
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install meson ninja gi-docgen PyGObject
      - name: configure_for_gcc
        if: ${{matrix.compiler == 'gcc'}}
        run: meson setup --buildtype=${{ matrix.buildtype}} --werror build/
        env:
          CC: gcc
          CXX: g++
      - name: configure_for_clang
        if: ${{matrix.compiler == 'clang'}}
        run: meson setup --buildtype=${{ matrix.buildtype}} --werror build/
        env:
          CC: clang
          CXX: clang++
      - name: Build
        run: xvfb-run meson compile -C build/
      - name: C Unit tests
        run: xvfb-run meson test -C build/ -v
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux_meson_testlog
          path: build/meson-logs/

#  see https://mesonbuild.com/Continuous-Integration.html
#  Compile-psylib-windows:
#    runs-on: windows-latest
