---
name: PsyLib compilation and test
run-name: ${{ github.actor }} is compiling and testing PsyLib
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  Compile-psy-lib-Linux:
    strategy:
      matrix:
        compiler: [gcc, clang]
        buildtype: [debug, release]
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libglib2.0-dev
          sudo apt install libgtk-4-dev
          sudo apt install libcunit1-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install meson ninja
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install meson ninja gi-docgen PyGObject
      - name: gcc build
        if: ${{ matrix.compiler }} == "gcc"
        env:
          CC: gcc
          CXX: g++
      - name: clang build
        if: ${{ matrix.compiler }} == "clang"
        env:
          CC: clang
          CXX: clang++
      - name: Configure
        run: meson setup --buildtype=${{ matrix.buildtype}} build/
      - name: Build
        run: xvfb-run meson compile -C build/
      - name: C Unit tests
        run: xvfb-run meson test -C build/ -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_meson_testlog
          path: build/meson-logs/testlog.txt

#  see https://mesonbuild.com/Continuous-Integration.html
#  Compile-psylib-windows:
#    runs-on: windows-latest
